Containerize nimbusapp and dependencies
Should allow running nimbusapp on any system with docker installed

diff --git a/docker/nimbusapp b/docker/nimbusapp
--- a/docker/nimbusapp
+++ b/docker/nimbusapp
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+# Debug mode, easy to get a shell without changing the entrypoint
+if [[ "$1" == "sh" ]]; then 
+    shift
+    exec bash "$@"
+    echo "Couldn't launch bash  (exit: $?)" >&2
+    exit 1
+fi
+
+# TODO: How should we handle docker hub?
+docker login
+
 function usage()
 {
     output "Usage: nimbusapp <IMAGE>:<VERSION> [OPTIONS] COMMAND"
